name: Deploy to Heroku (Strapi)

on:
  push:
    branches:
      - master
    paths:
      - "packages/strapi/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_STRAPI_APP_NAME }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-backend `git subtree split --prefix strapi master`:refs/heads/master --force
